kind: pipeline
type: docker
name: deploy organization service

steps:
  - name: remove-current-image
    image: docker/compose:1.29.2
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker rm -f $(docker ps -a -q --filter ancestor=ostock/organization-service:0.0.1-SNAPSHOT) 2>/dev/null || true
      - docker rmi -f ostock/organization-service:0.0.1-SNAPSHOT || true


  - name: build-docker-image
    image: maven:3.9-eclipse-temurin-17
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - apt-get update && apt-get install -y docker.io
      - mvn clean package -DskipTests

  - name: stop-existing-container
    image: docker/compose:1.29.2
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - cd /drone/src
      - docker-compose stop orgservice || true
      - docker-compose rm -f orgservice || true

  - name: start-new-container
    image: docker/compose:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - cd /drone/src
      - docker-compose up -d orgservice

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
